### PR TITLE
Add test/vader.vim to .gitignore

### PR DESCRIPTION
**Pull request by tweekmonster**

### CODE REVIEW

**Comment by mhinz** [comment]
Please add `test/vim` as well! (And I think you can omit the leading slash.)

**Comment by tweekmonster** [comment]
`test/vim` isn't created for me when I run `test/run`.  Am I missing something?

> (And I think you can omit the leading slash.)

I add it out of habit since it causes the ignored files to be rooted at the repo instead of matching anywhere in the file path.  But, I can remove it if you really hate it!

**Comment by mhinz** [comment]
The script clones and builds Vim, if it can't find it in `$PATH`! And you can leave the slash. :>

**Comment by tweekmonster** [comment]
You got it, boss.

**Comment by mhinz** [comment]
Thanks!

**Pull request merged**
